# common/src/main/resources/application-common.yml
spring:
  application:
    name: common-config
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: username
    password: password

mongo:
  uri: mongodb+srv://cluster0.vmbf6.mongodb.net/?authSource=%24external&authMechanism=MONGODB-X509&tls=true
  tls:
    cert: certificate/client.pem
    key: certificate/client-key.pem
  database: demo

app:
  secret:
    key: this_is_a_very_long_secret_key_256bit
    crypt:
      key: 1234567890123456
      user:
        key: qwertyuiop
  algorith1: AES
  algorith2: HmacSHA256
  address1: http://localhost:3000
  address2: http://localhost:3001
  security:
    roles: USER
    username: user
    crypt: bcrypt
  page:
    address: /privacy-policy
    service:
      about: http://about-service:8080
      auth: http://auth-service:8080
      activity: http://activity-service:8080
      logactivity: http://log-activity-service:8080
      points: http://points-service:8080
      register: http://register-service:8080
rabbit:
  exchange:
    name: notification-exchange
