# common/src/main/resources/application-common.yml
spring:
  application:
    name: common-config
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: username
    password: password
  mail:
    from: matteo.santangelo@colorsdev.tech
mongo:
  uri: mongodb+srv://cluster0.vmbf6.mongodb.net/?authSource=%24external&authMechanism=MONGODB-X509&tls=true
  tls:
    cert: certificate/client.pem
    key: certificate/client-key.pem
  database: demo

app:
  secret:
    key: this_is_a_very_long_secret_key_256bit
    crypt:
      key: 1234567890123456
      user:
        key: qwertyuiop
  algorithm1: AES
  algorithm2: HmacSHA256
  address1: http://localhost:3000
  address2: http://localhost:3001
  security:
    roles: USER
    username: user
    crypt: bcrypt
  page:
    address:
      policy: /privacy-policy
      home: /home
    service:
      image: http://image-service:8080
      auth: http://auth-service:8080
      activity: http://activity-service:8080
      userpoint: http://user-point-service:8080
      family: http://family-service:8080
    path:
      image: /api/image
      auth: /api/auth
      activity: /api/activity
      logactivity: /api/logactivity
      userpoint: /api/userpoint
      family: /api/family
  rabbitmq:
    notification:
      exchange:
        exchangeName: notification-exchange
rabbitmq:
  exchange:
    name:
      notification: notification-exchange
      point: point-exchange
    routingKey:
        notification: notification.family.notifier
        email: userpoint.notification.email
        point: point.log.activity
message:
  error:
    generic: Errore generico
cloudinary:
  cloud_name: dzxtjigpc
  api_key: 793323621769757
  api_secret: Prx1G26HHyxr-WSKzyvkmjfNzqA
email:
  username: activity.manager.example@gmail.com
  password: jurh wogf tgef nlas

