services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Porta per la comunicazione con l'app
      - "15672:15672" # Interfaccia di gestione web
    environment:
      - 'RABBITMQ_DEFAULT_PASS=password'
      - 'RABBITMQ_DEFAULT_USER=username'
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - register-service
      - about-service
      - user-point-service
      - activity-service
      - log-activity-service
      - auth-service
      - family-service
      - notification-service
    networks:
      - app-network
  register-service:
    depends_on:
      - rabbitmq
    image: register-service:1.0.0
    build:
      context: ./
      dockerfile: service/register/Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
    volumes:
      - ./service/register/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
    networks:
      - app-network

  about-service:
    depends_on:
      - rabbitmq  
    image: about-service:1.0.0
    build:
      context: ./
      dockerfile: service/about/Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
    volumes:
      - ./service/family/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
    networks:
      - app-network

  user-point-service:
    depends_on:
      - rabbitmq  
    image: user-point-service:1.0.0
    build:
      context: ./
      dockerfile: service/userPoint/Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
    volumes:
      - ./service/userPoint/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
    networks:
      - app-network

  activity-service:
    depends_on:
      - rabbitmq 
    image: activity-service:1.0.0
    build:
      context: ./
      dockerfile: service/activity/Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
    volumes:
      - ./service/activity/src/main/resources/certificate:/app/certificate
    networks:
      - app-network

  log-activity-service:
    depends_on:
      - rabbitmq
    image: log-activity-service:1.0.0
    build:
      context: ./
      dockerfile: service/logActivity/Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
    volumes:
      -  ./service/logActivity/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
    networks:
      - app-network

  auth-service:   
    depends_on:
      - rabbitmq  
    image: auth-service:1.0.0
    build:
      context: ./
      dockerfile: service/auth/Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
    volumes:
      - ./service/auth/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
    networks:
      - app-network

  family-service:
    depends_on:
      - rabbitmq
    image: family-service:1.0.0
    build:
      context: ./
      dockerfile: service/family/Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
    volumes:
      - ./service/family/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
    networks:
      - app-network

  notification-service:
    depends_on:
      - rabbitmq 
    image: notification-service:1.0.0
    build:
      context: ./
      dockerfile: service/notification/Dockerfile   
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
    volumes:
      - ./service/notification/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    external: true
