version: '3.8'

services:

  register-service:
    image: register-service:1.0.0
    build:
      context: ./
      dockerfile: service/register/Dockerfile
    ports:
      - "8081:8080"
      - "5005:5005"  # Porta per debug
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - app-network

  about-service:
    image: about-service:1.0.0
    build:
      context: ./
      dockerfile: service/about/Dockerfile
    ports:
      - "8082:8080"
      - "5007:5007"  # Porta per debug
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007
    networks:
      - app-network

  points-service:
    image: points-service:1.0.0
    build:
      context: ./
      dockerfile: service/points/Dockerfile
    ports:
      - "8083:8080"
      - "5006:5006"  # Porta per debug
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    networks:
      - app-network

  activity-service:
    image: activity-service:1.0.0
    build:
      context: ./
      dockerfile: service/activity/Dockerfile
    ports:
      - "8084:8080"
      - "5008:5008"  # Porta per debug
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008
    networks:
      - app-network

  logactivity-service:
    image: log-activity-service:1.0.0
    build:
      context: ./
      dockerfile: service/logActivity/Dockerfile
    ports:
      - "8085:8080"
      - "5009:5009"  # Porta per debug
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5009
    networks:
      - app-network

  auth-service:
    image: auth-service:1.0.0
    build:
      context: ./
      dockerfile: service/auth/Dockerfile
    ports:
      - "8086:8080"
      - "5010:5010"  # Porta per debug
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5010
    networks:
      - app-network

  family-service:
    image: family-service:1.0.0
    build:
      context: ./
      dockerfile: service/family/Dockerfile
    ports:
      - "8087:8080"
      - "5011:5011"  # Porta per debug
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5011
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
