# DOCKER COMPOSE PER DEBUGGING
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Porta per la comunicazione con l'app
      - "15672:15672" # Interfaccia di gestione web
    environment:
      - 'RABBITMQ_DEFAULT_PASS=password'
      - 'RABBITMQ_DEFAULT_USER=username'
    networks:
      - app-network

register-service:
    depends_on:
      - rabbitmq
image: register-service:1.0.0
build:
context: ./
@@ -12,12 +26,18 @@ services:
- "5005:5005"  # Porta per debug
environment:
- JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
volumes:
- ./service/register/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
networks:
- app-network

about-service:
    depends_on:
      - rabbitmq
image: about-service:1.0.0
build:
context: ./
@@ -27,12 +47,18 @@ services:
- "5007:5007"  # Porta per debug
environment:
- JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
volumes:
- ./service/family/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
networks:
- app-network

points-service:
    depends_on:
      - rabbitmq
image: points-service:1.0.0
build:
context: ./
@@ -42,12 +68,18 @@ services:
- "5006:5006"  # Porta per debug
environment:
- JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
volumes:
- ./service/points/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
networks:
- app-network

activity-service:
    depends_on:
      - rabbitmq
image: activity-service:1.0.0
build:
context: ./
@@ -57,12 +89,18 @@ services:
- "5008:5008"  # Porta per debug
environment:
- JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
volumes:
- ./service/activity/src/main/resources/certificate:/app/certificate
networks:
- app-network

logactivity-service:
    depends_on:
      - rabbitmq
image: log-activity-service:1.0.0
build:
context: ./
@@ -72,12 +110,18 @@ services:
- "5009:5009"  # Porta per debug
environment:
- JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5009
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
volumes:
-  ./service/logActivity/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
networks:
- app-network

auth-service:
    depends_on:
      - rabbitmq
image: auth-service:1.0.0
build:
context: ./
@@ -87,12 +131,18 @@ services:
- "5010:5010"  # Porta per debug
environment:
- JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5010
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
volumes:
- ./service/auth/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
networks:
- app-network

family-service:
    depends_on:
      - rabbitmq
image: family-service:1.0.0
build:
context: ./
@@ -102,11 +152,36 @@ services:
- "5011:5011"  # Porta per debug
environment:
- JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5011
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
volumes:
- ./service/family/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
networks:
- app-network

  notification-service:
    depends_on:
      - rabbitmq
    image: notification-service:1.0.0
    build:
      context: ./
      dockerfile: service/notification/Dockerfile
    ports:
      - "8088:8080"
      - "5012:5012"  # Porta per debug
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5012
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
    volumes:
      - ./service/notification/src/main/resources/certificate:/app/certificate  # Monta i certificati nel path giusto
    networks:
      - app-network

networks:
app-network:
driver: bridge