# common/src/main/resources/application-common.yml
spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: activityManager
  codec:
    max-in-memory-size: 16MB
