# common/src/main/resources/application-common.yml
spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: activityManager
session:
  attribute:
    identification: "id"
websocket:
  path: "ws/notifications"
