# common/src/main/resources/application-common.yml
spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: activityManager
order:
  type1: "date"
app:
  rabbitmq:
    exchange:
      point:
        exchangeName: point-exchange
        routingKey:
          logActivity: point.log.activity
          logFamily: point.log.family
message:
  http:
    error: "Errore HTTP: "

