# common/src/main/resources/application-common.yml
spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: activityManager
error:
  document:
    notFound: "Documento non trovato con identificativo: "
    points: "I Point a disposizione sono: "
    arithmetic: I punti devono essere maggiori o uguali a zero.
