# common/src/main/resources/application-common.yml
spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: activityManager
message:
  document:
    points: "?numero_punti?"
    add: "?aggiunti_punti?"
    remove: "?sottratti_punti?"
notification:
  service: "familyService"
