# common/src/main/resources/application-common.yml
spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: activityManager
message:
  document:
    points: "I Point a disposizione sono: "
    add: " Punti aggiunti da "
    remove: " Punti sottratti da  "
notification:
  service: "familyService"
