# common/src/main/resources/application-common.yml
spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: activityManager
app:
  rabbitmq:
    exchange: notification-exchange
    routingKey: notification.family
message:
  document:
    points: "I Points a disposizione sono: "
    add: " Punti aggiunti da "
    remove: " Punti sottratti da  "
notification:
  service: "familyService"
