# common/src/main/resources/application-common.yml
spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: activityManager
message:
  document:
    points: "?lang?numero_punti?lang?"
    add: "?lang?aggiunti_punti?lang?"
    remove: "?lang?sottratti_punti?lang?"
notification:
  service: "familyService"
