spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: activityManager
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: username
    password: password

error:
  http: "Errore HTTP: "
  document:
    notFound: 'Documento non trovato con identificativo: '

app:
  rabbitmq:
    exchange:
      point:
        exchangeName: point-exchange
        routingKey:
          logActivity: point.log.activity
          logFamily: point.log.family
          commandSaveActivity: activity.save
          commandDeleteActivity: activity.delete
  elasticsearch:
    enabled: "true"
