# common/src/main/resources/application-common.yml
spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: activityManager
error:
  http: "Errore HTTP: "
  document:
    notFound: 'Documento non trovato con identificativo: '
app:
  rabbitmq:
    exchange:
      point:
        exchangeName: point-exchange
        routingKey:
          logActivity: point.log.activity
          logFamily: point.log.family